### ISSUE TITLE
Browser becomes unusable after some time

### ISSUE THREAD

**Issue by vvo** [camilleanelli/big-store#42]
Hi! Strangely, after some queries and categories selection my browser becomes unusable. Also a LOT of queries are made for each letter.

Do you know how to fix it?

Thanks!

**Comment by camilleanelli** [comment]
Hello ,

Yes I am going to fix it, with debounce() for the queries, and see what's happening in my code.

**Comment by camilleanelli** [comment]
Hello,

I rolled back previous changes and it fixed the problem. There was clearly a bug in my code. I am still investigating why it produced so much requests. I will add the debounce function now.

 Thank you for catching the bug and sorry for the inconvenience :)
